import { DM_Sans } from "next/font/google";
import localfont from "next/font/local";
import "../globals.css";
import { Header } from "../components/header/Header";
import { Footer } from "../components/footer/Footer";
import Head from "next/head";

const circularStd = localfont({
  src: "../../../public/fonts/CircularStd-Book.woff",
  variable: "--circularStd",
});

const circularItalic = localfont({
  src: "../../../public/fonts/CircularStd-MediumItalic.woff2",
  variable: "--circularItalic",
});

const circularBold = localfont({
  src: "../../../public/fonts/CircularStd-Bold.woff",
  variable: "--circularBold",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Frank And Oak USA - Frank And Oak USA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${circularStd.variable} ${circularItalic.variable} ${circularBold.variable} font-circularStd tracking-[-0.022em] antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
